// ============================================================
// THE DREYFUSS EFFECT — article corpus
// ============================================================
window.DATA = {
  sections: {
    science: {
      slug: "science",
      title: "Science",
      kicker: "Of the Natural World",
      emblem: "S",
      blurb: "Reports from the uncharted universe. Where collaboration and curiosity measure mystery. The more we investigate, the greater our license to interpolate.",
    },
    history: {
      slug: "history",
      title: "History",
      kicker: "Of Times Past",
      emblem: "H",
      blurb: "Reflections from the distant past and disputed present. Wisdom lies where truth and repetition meet. The pursuit of tomorrow begins with the study of yesterday.",
    },
    commerce: {
      slug: "commerce",
      title: "Commerce",
      kicker: "Of Trade",
      emblem: "C",
      blurb: "Reckonings of Industry and Ingenuity. Exploration exhibits the nuance behind class and capital. Transaction turns character and currency into consequence.",
    },
  },
  articles: [
    // ---- SCIENCE ----
    {
      id: "octopus-mind",
      section: "science",
      title: "On the Lonely Geometry of the Octopus Mind",
      titleHtml: "On the Lonely Geometry <br/>of the <em>Octopus Mind</em>",
      dek: "Two-thirds of its neurons lie not in the brain but in the arms. What does cognition look like when it cannot agree with itself?",
      author: "M. Aleria Cromwell",
      date: "May 14, 2026",
      sortDate: "2026-05-14",
      readTime: "14 min",
      popularity: 94,
      kicker: "Cephalopoda",
      glyph: "✦",
    },
    {
      id: "cartographers",
      section: "science",
      title: "The Last Cartographers of Coastline",
      titleHtml: "The Last Cartographers <br/>of <em>Coastline</em>",
      dek: "Every map of a shore is a map of a year. The surveyors who measure what the sea is taking, and the strange peace they find in the work.",
      author: "Hollis Karr",
      date: "May 7, 2026",
      sortDate: "2026-05-07",
      readTime: "11 min",
      popularity: 71,
      kicker: "Geomorphology",
      glyph: "⚓",
    },
    {
      id: "lichen",
      section: "science",
      title: "What the Lichen Knows",
      titleHtml: "What the <em>Lichen</em> Knows",
      dek: "A fungus and an alga, neither alive in any sense the other recognizes — and yet the oldest organisms on the rock. A meditation on cooperation older than language.",
      author: "Dr. Severin Halstead",
      date: "April 24, 2026",
      sortDate: "2026-04-24",
      readTime: "9 min",
      popularity: 88,
      kicker: "Symbiosis",
      glyph: "❦",
    },
    {
      id: "forgetting",
      section: "science",
      title: "A Brief History of Forgetting",
      titleHtml: "A Brief History <br/>of <em>Forgetting</em>",
      dek: "Sleep does not merely rest the mind. It edits it — and the editors, it now seems, have a literary sensibility we are only beginning to read.",
      author: "Iona Whitfield",
      date: "April 11, 2026",
      sortDate: "2026-04-11",
      readTime: "13 min",
      popularity: 81,
      kicker: "Neuroscience",
      glyph: "✶",
    },
    {
      id: "quietest-room",
      section: "science",
      title: "The Quietest Room in the World",
      titleHtml: "The Quietest Room <br/>in the <em>World</em>",
      dek: "Inside an anechoic chamber in Minneapolis, you can hear your own blood. Few visitors stay an hour. What the engineers of silence have learned from those who could not bear it.",
      author: "P. J. Tournier",
      date: "March 28, 2026",
      sortDate: "2026-03-28",
      readTime: "8 min",
      popularity: 66,
      kicker: "Psychoacoustics",
      glyph: "◈",
    },
    {
      id: "tardigrade",
      section: "science",
      title: "The Animal That Cannot Be Killed",
      titleHtml: "The Animal That <br/>Cannot Be <em>Killed</em>",
      dek: "Boiled, frozen, vacuumed into space, irradiated — and yet the tardigrade persists, indifferent. A small thesis on what it means to be merely alive.",
      author: "Margery Hessen",
      date: "March 14, 2026",
      sortDate: "2026-03-14",
      readTime: "10 min",
      popularity: 77,
      kicker: "Extremophiles",
      glyph: "✺",
    },

    // ---- HISTORY ----
    {
      id: "clerk-byzantine",
      section: "history",
      title: "The Clerk Who Saw the Empire End",
      titleHtml: "The Clerk Who Saw <br/>the <em>Empire End</em>",
      dek: "From the household ledgers of a middling Byzantine functionary, May 1453: the price of cabbage, a daughter's dowry, and the morning the walls came down.",
      author: "Reverdy Aitchison",
      date: "May 19, 2026",
      sortDate: "2026-05-19",
      readTime: "16 min",
      popularity: 91,
      kicker: "Constantinople",
      glyph: "†",
    },
    {
      id: "salt-silver",
      section: "history",
      title: "Salt, Silver, and the First Globalization",
      titleHtml: "Salt, Silver, &amp; the <br/>First <em>Globalization</em>",
      dek: "Long before the container ship, the world was already small. A mountain in Bolivia paid for a war in Flanders and a porcelain bowl in Macau.",
      author: "Helene Quintus",
      date: "May 2, 2026",
      sortDate: "2026-05-02",
      readTime: "18 min",
      popularity: 73,
      kicker: "Potosí",
      glyph: "❉",
    },
    {
      id: "library-burned",
      section: "history",
      title: "The Library That Burned Twice",
      titleHtml: "The Library That <br/>Burned <em>Twice</em>",
      dek: "Alexandria, of course. But also Sarajevo, August 1992. What a city loses when it loses its catalog, and the librarians who carry it anyway.",
      author: "Ottavio del Vecchio",
      date: "April 18, 2026",
      sortDate: "2026-04-18",
      readTime: "12 min",
      popularity: 85,
      kicker: "Memory",
      glyph: "✠",
    },
    {
      id: "westphalia-letters",
      section: "history",
      title: "Letters from a Forgotten Treaty",
      titleHtml: "Letters from a <br/>Forgotten <em>Treaty</em>",
      dek: "The peace of Westphalia did not end a war so much as exhaust one. The diplomats' correspondence — querulous, hungry, brilliant — reads like a slow-motion novel.",
      author: "Florian Mahr",
      date: "April 3, 2026",
      sortDate: "2026-04-03",
      readTime: "15 min",
      popularity: 62,
      kicker: "1648",
      glyph: "❧",
    },
    {
      id: "marginalia-empire",
      section: "history",
      title: "Marginalia of Empire",
      titleHtml: "Marginalia <br/>of <em>Empire</em>",
      dek: "Beside the official record of the East India Company, a quieter archive: the scribbled doubts, jokes, and complaints of the men who kept its books.",
      author: "Ananya Dunmore",
      date: "March 20, 2026",
      sortDate: "2026-03-20",
      readTime: "11 min",
      popularity: 79,
      kicker: "Archives",
      glyph: "☙",
    },
    {
      id: "weather-revolution",
      section: "history",
      title: "On the Weather of Revolutions",
      titleHtml: "On the Weather <br/>of <em>Revolutions</em>",
      dek: "1789 was the coldest winter in a hundred years. 1917 the wettest spring. History is in part a meteorology — a story of which crowds were willing to stand outside.",
      author: "Béatrice Lammel",
      date: "March 6, 2026",
      sortDate: "2026-03-06",
      readTime: "10 min",
      popularity: 68,
      kicker: "Climate",
      glyph: "✦",
    },

    // ---- COMMERCE ----
    {
      id: "tulip",
      section: "commerce",
      title: "The Tulip Was Never About Tulips",
      titleHtml: "The Tulip Was Never <br/>About <em>Tulips</em>",
      dek: "Three hundred years on, Tulpenmanie is still the lazy metaphor of choice. But the bulb traders of Haarlem were doing something stranger than gambling — and we are still doing it.",
      author: "Wim van Doorn",
      date: "May 21, 2026",
      sortDate: "2026-05-21",
      readTime: "13 min",
      popularity: 96,
      kicker: "Speculation",
      glyph: "❀",
    },
    {
      id: "ledger-literature",
      section: "commerce",
      title: "The Ledger as Literature",
      titleHtml: "The Ledger as <br/><em>Literature</em>",
      dek: "Double-entry bookkeeping was invented in Venice and announced, with quiet seriousness, a new kind of narrative. Two columns, two truths — and a tension between them that has not yet released.",
      author: "Pier Lorenzo Massei",
      date: "May 10, 2026",
      sortDate: "2026-05-10",
      readTime: "12 min",
      popularity: 74,
      kicker: "Accounting",
      glyph: "❦",
    },
    {
      id: "hanseatic",
      section: "commerce",
      title: "What the Hanseatic League Understood",
      titleHtml: "What the Hanseatic <br/><em>League</em> Understood",
      dek: "Before the corporation, before the nation, a network of merchant towns ran the North Sea on trust, salt, and reputation. The platform business is older than we think.",
      author: "Linnea Reichert",
      date: "April 27, 2026",
      sortDate: "2026-04-27",
      readTime: "14 min",
      popularity: 70,
      kicker: "Networks",
      glyph: "✺",
    },
    {
      id: "coffeehouses",
      section: "commerce",
      title: "Of Coffeehouses and Insurance",
      titleHtml: "Of Coffeehouses <br/>&amp; <em>Insurance</em>",
      dek: "Edward Lloyd ran a coffeehouse near the docks. The men who drank there were trying, between bowls of stew, to put a price on the sea.",
      author: "Cordelia Marwood",
      date: "April 9, 2026",
      sortDate: "2026-04-09",
      readTime: "11 min",
      popularity: 82,
      kicker: "Lloyd's",
      glyph: "◉",
    },
    {
      id: "monasteries",
      section: "commerce",
      title: "The Patient Capital of Monasteries",
      titleHtml: "The Patient Capital <br/>of <em>Monasteries</em>",
      dek: "Cistercians planted vineyards their great-grandchildren would harvest. What modern capital, in its impatience, has forgotten — and what it might still relearn.",
      author: "Brother Anselm O.S.B.",
      date: "March 22, 2026",
      sortDate: "2026-03-22",
      readTime: "9 min",
      popularity: 64,
      kicker: "Long horizons",
      glyph: "✠",
    },
    {
      id: "coinage",
      section: "commerce",
      title: "The Lyric Life of Coinage",
      titleHtml: "The Lyric Life <br/>of <em>Coinage</em>",
      dek: "A coin is the smallest portable poem a state can issue. From the owl of Athens to the buffalo of Buffalo, NY — what nations chose to press, and why.",
      author: "Eustace Reardon",
      date: "March 1, 2026",
      sortDate: "2026-03-01",
      readTime: "10 min",
      popularity: 58,
      kicker: "Numismatics",
      glyph: "◈",
    },
  ],

  // Article body (used for the demo reader). Other articles link back to a stub.
  bodies: {
    "octopus-mind": [
      "There is, in the long argument the natural sciences have with themselves about what minds are for, a small and difficult animal that refuses to be a footnote. The common octopus — *Octopus vulgaris*, a name as ill-fitting as any in the binomial registry — possesses some five hundred million neurons. Two-thirds of them lie outside its brain.",
      "They are distributed, instead, into the eight arms. Each arm, having its own swelling of nerve tissue, can taste, decide, recoil, reach. It can solve a puzzle of which the brain in the center of the body has not yet been informed. It can, in the technical sense, change its mind without consulting itself.",
      { type: "h2", text: "On the architecture of disagreement" },
      "What troubles the biologists, when they let themselves be troubled, is not the strangeness of this so much as its plausibility. Mind, we have long argued, is a unitary thing — a *thinking it*, in Descartes' phrase, located behind the eyes. The octopus is a polite refutation. It moves as one. It hunts as eight. It is, by every measure we know how to apply, awake; and there is no single place inside it where the lights are on.",
      "<blockquote>Consider, if you will, the possibility that the mind has always been a confederation. The octopus is only honest about it.</blockquote>",
      "I spent three days last August in the marine laboratory at Naples, in a room whose temperature was held at a careful sixteen degrees. The tank held a young female who had been there long enough to have opinions about the staff. She liked the postdoc from Lisbon and disliked, in a sustained and theatrical way, the German technician who fed her. She would change color when he entered the room. She would extend an arm, very slowly, as if to point.",
      { type: "h2", text: "The problem of the second self" },
      "It is not difficult to project intelligence onto an animal that watches you. What is difficult is to imagine the geometry of that intelligence from the inside — to imagine a self that is also, in some practical sense, a small parliament. The neuroscientist Peter Godfrey-Smith has written that the octopus is the closest thing we have to meeting an intelligent alien. I think this is true and I think it understates the matter. The alien lives inside our own ocean.",
      "There is a parable here for our own species, which has always been more comfortable with the *fiction* of a unified self than with the *fact* of one. Every act of attention is a delegation; every emotion, a region of the body putting in a vote. The octopus is not, in this respect, more divided than we are. It is merely less embarrassed.",
      { type: "break" },
      "What does it mean to *know* something, in eight places at once, that none of those places can put into a sentence? The question has not been answered. It may not be answerable in our register. But the octopus, indifferent to the question, continues. She unfolds. She reaches. She decides — wherever, in her quiet republic, decision happens to live that afternoon — and the arm goes where it goes, and the rest of her finds out in time.",
    ],
  },
};
